# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Scouting Application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Scouting Application
  pod 'QRCode'
  pod 'AsyncTimer'

  target 'Scouting ApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Scouting ApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
